name              = "epiaccess-map-worker"
account_id        = "98f15cd6db7d231fee6a12ada3cac990"          # ⬅︎ see step 2 below
compatibility_date = "2025-06-05"
workers_dev       = false                      # ⬅︎ top-level

[assets]
directory = "./public"

[[routes]]
pattern   = "epiaccess.org/epimap/*"
zone_name = "epiaccess.org"
